<template>
  <div class="page-shell">
    <div class="page-heading"><div><h1>房东认证</h1><p>首次申请通过后启用房东账号；已有房东可把新房屋追加到原账号。</p></div></div>
    <section class="panel">
      <div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="申请人、手机号、证件或房屋" style="width:300px"/><el-select v-model="query.status" clearable placeholder="审核状态" style="width:145px"><el-option v-for="(v,k) in statuses" :key="k" :label="v" :value="k"/></el-select><el-button @click="load"><el-icon><Search/></el-icon>查询</el-button></div>
      <div class="table-wrap"><el-table :data="page.records" v-loading="loading"><el-table-column prop="applicantName" label="申请人" width="110"/><el-table-column prop="phone" label="房东账号" width="130"/><el-table-column label="申请类型" width="120"><template #default="s"><el-tag :type="s.row.applicationType==='NEW'?'primary':'success'">{{applicationTypes[s.row.applicationType]}}</el-tag></template></el-table-column><el-table-column prop="houseName" label="认证房屋" min-width="240"/><el-table-column label="材料" width="90"><template #default="s"><el-tag :type="s.row.attachment?'success':'info'">{{s.row.attachment?'已上传':'未上传'}}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="statusType[s.row.status]">{{statuses[s.row.status]}}</el-tag></template></el-table-column><el-table-column prop="reviewerName" label="审核人" width="100"/><el-table-column prop="createdAt" label="提交时间" width="170"/><el-table-column label="操作" width="100"><template #default="s"><el-button link type="primary" @click="openReview(s.row)">{{s.row.status==='PENDING'?'审核':'查看'}}</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.pageNum" :total="page.total" layout="total,prev,pager,next" @current-change="load"/></div></div>
    </section>
    <el-dialog v-model="reviewDialog" title="房东认证审核" width="600px">
      <el-descriptions :column="1" border><el-descriptions-item label="申请类型">{{applicationTypes[current.applicationType]}}</el-descriptions-item><el-descriptions-item label="申请人">{{current.applicantName}}</el-descriptions-item><el-descriptions-item label="房东账号">{{current.accountUsername}}</el-descriptions-item><el-descriptions-item label="身份证号"><span class="mono">{{current.idCard}}</span></el-descriptions-item><el-descriptions-item label="认证房屋">{{current.houseName}}</el-descriptions-item></el-descriptions>
      <section class="material"><b>认证材料</b><el-image v-if="isImage(current.attachment)" :src="current.attachment" :preview-src-list="[current.attachment]" fit="cover" preview-teleported/><a v-else-if="current.attachment" :href="current.attachment" target="_blank" rel="noopener"><el-icon><Document/></el-icon>打开PDF证明</a><span v-else>未上传附件</span></section>
      <el-form v-if="current.status==='PENDING'" label-width="85px"><el-form-item label="审核结果"><el-radio-group v-model="review.status"><el-radio value="APPROVED">审核通过</el-radio><el-radio value="REJECTED">审核驳回</el-radio></el-radio-group></el-form-item><el-form-item label="审核意见"><el-input v-model="review.comment" type="textarea" :rows="4"/></el-form-item></el-form>
      <el-alert v-else :title="`审核结果：${statuses[current.status]}；${current.reviewComment||'未填写意见'}`" :type="current.status==='APPROVED'?'success':'error'" show-icon :closable="false" style="margin-top:16px"/>
      <template #footer><el-button @click="reviewDialog=false">关闭</el-button><el-button v-if="current.status==='PENDING'" type="primary" @click="submitReview">确认审核</el-button></template>
    </el-dialog>
  </div>
</template>
<script setup>
import{onMounted,reactive,ref}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import http from'../api/http';const statuses={PENDING:'待审核',APPROVED:'已通过',REJECTED:'已驳回'},statusType={PENDING:'warning',APPROVED:'success',REJECTED:'danger'},applicationTypes={NEW:'首次注册',EXISTING:'追加房屋'},query=reactive({pageNum:1,pageSize:10,keyword:'',status:''}),page=reactive({records:[],total:0}),loading=ref(false),reviewDialog=ref(false),current=ref({}),review=reactive({status:'APPROVED',comment:''});onMounted(load);async function load(){loading.value=true;try{Object.assign(page,await http.get('/owner-applications',{params:query}))}finally{loading.value=false}}function openReview(row){current.value=row;review.status='APPROVED';review.comment='';reviewDialog.value=true}async function submitReview(){const result=await http.put(`/owner-applications/${current.value.id}/review`,review);reviewDialog.value=false;load();if(result.accountActivated)await ElMessageBox.alert(`房东账号已启用并绑定房屋。\n登录账号：${result.username}\n初始密码：123456`,'认证通过',{type:'success'});else if(result.username)await ElMessageBox.alert(`新房屋已绑定到原房东账号：${result.username}`,'认证通过',{type:'success'});else ElMessage.success('审核完成')}function isImage(url){return/\.(png|jpe?g|gif)(?:\?.*)?$/i.test(url||'')}
</script>
<style scoped>.material{display:flex;align-items:center;gap:14px;margin:16px 0;padding:14px;border:1px solid #dce8e7;border-radius:10px;background:#f3f8f7}.material>b{font-size:12px;color:#45657a}.material :deep(.el-image){width:110px;height:82px;border-radius:8px;cursor:zoom-in}.material>a{display:flex;align-items:center;gap:7px;color:#0e8a7a;text-decoration:none}.material>span{color:#8a9ba4;font-size:12px}@media(max-width:600px){.material{align-items:flex-start;flex-direction:column}.material :deep(.el-image){width:100%;height:160px}}</style>
