<template>
  <div class="page-shell"><div class="page-heading"><div><h1>居住证办理</h1><p>模拟申请、审核、通过和领取的完整线上办理流程。</p></div><el-button v-if="auth.role==='TENANT'" type="primary" @click="openApply"><el-icon><Plus/></el-icon>申请居住证</el-button></div><section class="panel"><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="申请人、手机号或房屋" style="width:260px"/><el-select v-model="query.status" clearable placeholder="办理状态" style="width:150px"><el-option v-for="(v,k) in statuses" :key="k" :label="v" :value="k"/></el-select><el-button @click="load"><el-icon><Search/></el-icon>查询</el-button></div><div class="table-wrap"><el-table :data="page.records" v-loading="loading"><el-table-column prop="applicantName" label="申请人" width="110"/><el-table-column prop="houseName" label="居住房屋" min-width="220"/><el-table-column prop="reason" label="申请原因" min-width="220" show-overflow-tooltip/><el-table-column label="办理状态" width="110"><template #default="s"><el-tag :type="statusType[s.row.status]">{{statuses[s.row.status]}}</el-tag></template></el-table-column><el-table-column prop="reviewerName" label="办理民警" width="110"/><el-table-column prop="createdAt" label="申请时间" width="170"/><el-table-column label="操作" width="150"><template #default="s"><el-button v-if="['ADMIN','POLICE'].includes(auth.role)" link type="primary" @click="openReview(s.row)">更新状态</el-button><el-button link @click="current=s.row;detailDialog=true">进度</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.pageNum" :total="page.total" layout="total,prev,pager,next" @current-change="load"/></div></div></section>
    <el-dialog v-model="applyDialog" title="申请居住证" width="540px"><el-form ref="formRef" :model="form" :rules="rules" label-width="90px"><el-form-item label="居住房屋" prop="houseId"><el-select v-model="form.houseId" style="width:100%"><el-option v-for="h in houses" :key="h.id" :label="h.label" :value="h.id"/></el-select></el-form-item><el-form-item label="申请原因" prop="reason"><el-input v-model="form.reason" type="textarea" :rows="4"/></el-form-item><el-form-item label="证明附件"><el-upload action="/api/files/upload" :headers="uploadHeaders" :limit="1" :on-success="uploaded"><el-button>上传图片或PDF</el-button></el-upload></el-form-item></el-form><template #footer><el-button @click="applyDialog=false">取消</el-button><el-button type="primary" @click="apply">提交申请</el-button></template></el-dialog>
    <el-dialog v-model="reviewDialog" title="更新办理状态" width="480px"><el-form label-width="90px"><el-form-item label="办理状态"><el-select v-model="review.status" style="width:100%"><el-option v-for="(v,k) in reviewStatuses" :key="k" :label="v" :value="k"/></el-select></el-form-item><el-form-item label="办理意见"><el-input v-model="review.comment" type="textarea" :rows="4"/></el-form-item></el-form><template #footer><el-button @click="reviewDialog=false">取消</el-button><el-button type="primary" @click="submitReview">保存状态</el-button></template></el-dialog>
    <el-dialog v-model="detailDialog" title="办理进度" width="520px"><el-steps :active="stepIndex(current.status)" align-center finish-status="success"><el-step title="已提交"/><el-step title="审核中"/><el-step title="已通过"/><el-step title="已领取"/></el-steps><el-alert v-if="current.status==='REJECTED'" style="margin-top:25px" type="error" :title="`申请已驳回：${current.reviewComment||'未填写原因'}`" show-icon :closable="false"/></el-dialog>
  </div>
</template>
<script setup>
import{computed,onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import http from'../api/http';import{useAuthStore}from'../stores/auth';const auth=useAuthStore(),statuses={PENDING:'待审核',PROCESSING:'审核中',APPROVED:'已通过',REJECTED:'已驳回',COLLECTED:'已领取'},reviewStatuses={PROCESSING:'审核中',APPROVED:'已通过',REJECTED:'已驳回',COLLECTED:'已领取'},statusType={PENDING:'warning',PROCESSING:'primary',APPROVED:'success',REJECTED:'danger',COLLECTED:'info'},query=reactive({pageNum:1,pageSize:10,keyword:'',status:''}),page=reactive({records:[],total:0}),loading=ref(false),houses=ref([]),applyDialog=ref(false),reviewDialog=ref(false),detailDialog=ref(false),reviewId=ref(null),current=ref({}),formRef=ref(),form=reactive({houseId:null,tenancyId:null,reason:'因在本市长期工作和生活，申请办理居住证。',attachment:''}),review=reactive({status:'PROCESSING',comment:''}),rules={houseId:[{required:true,message:'请选择房屋'}],reason:[{required:true,message:'请填写申请原因'}]},uploadHeaders=computed(()=>({Authorization:`Bearer ${auth.token}`}));onMounted(async()=>{houses.value=await http.get('/houses/options');load()});async function load(){loading.value=true;try{Object.assign(page,await http.get('/permits',{params:query}))}finally{loading.value=false}}function openApply(){applyDialog.value=true}function uploaded(res){if(res.code===0)form.attachment=res.data.url}async function apply(){await formRef.value.validate();await http.post('/permits',form);ElMessage.success('申请已提交');applyDialog.value=false;load()}function openReview(row){reviewId.value=row.id;review.status=row.status==='PENDING'?'PROCESSING':row.status;review.comment=row.reviewComment||'';reviewDialog.value=true}async function submitReview(){await http.put(`/permits/${reviewId.value}/review`,review);ElMessage.success('办理状态已更新');reviewDialog.value=false;load()}function stepIndex(s){return{PENDING:1,PROCESSING:2,APPROVED:3,COLLECTED:4}[s]||1}
</script>
