<template>
  <div class="page-shell"><div class="page-heading"><div><h1>承租人管理</h1><p>查看当前承租人和历史租住信息，人员迁出后仍保留档案。</p></div><el-button v-if="['ADMIN','POLICE'].includes(auth.role)" type="primary" @click="open()"><el-icon><Plus/></el-icon>新增档案</el-button></div>
    <section class="panel"><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="姓名、手机号或身份证号" style="width:270px"/><el-select v-model="query.status" clearable placeholder="居住状态" style="width:150px"><el-option v-for="(v,k) in statuses" :key="k" :label="v" :value="k"/></el-select><el-button @click="load"><el-icon><Search/></el-icon>查询</el-button><el-button @click="reset">重置</el-button><el-button v-if="auth.role==='OWNER'" type="primary" plain @click="$router.push('/tenancies')">登记新承租人</el-button></div>
      <div class="table-wrap"><el-table :data="page.records" v-loading="loading"><el-table-column prop="name" label="姓名" min-width="100"/><el-table-column prop="gender" label="性别" width="70"/><el-table-column prop="phone" label="手机号" width="130"/><el-table-column prop="idCard" label="身份证号" min-width="175"><template #default="s"><span class="mono">{{maskId(s.row.idCard)}}</span></template></el-table-column><el-table-column prop="hometown" label="户籍地" min-width="140"/><el-table-column prop="houseName" label="最近租住房屋" min-width="220"/><el-table-column prop="ownerName" label="房东" width="100"/><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="statusType[s.row.status]">{{statuses[s.row.status]||'未入住'}}</el-tag></template></el-table-column><el-table-column v-if="['ADMIN','POLICE'].includes(auth.role)" label="操作" width="90"><template #default="s"><el-button link type="primary" @click="open(s.row)">编辑</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.pageNum" :total="page.total" layout="total,prev,pager,next" @current-change="load"/></div></div></section>
    <el-dialog v-model="dialog" :title="editing?'编辑承租人档案':'新增承租人档案'" width="590px"><el-form ref="formRef" :model="form" :rules="rules" label-width="90px"><el-row :gutter="14"><el-col :span="12"><el-form-item label="姓名" prop="name"><el-input v-model="form.name"/></el-form-item></el-col><el-col :span="12"><el-form-item label="性别"><el-select v-model="form.gender" style="width:100%"><el-option label="男" value="男"/><el-option label="女" value="女"/></el-select></el-form-item></el-col></el-row><el-form-item label="手机号" prop="phone"><el-input v-model="form.phone"/></el-form-item><el-form-item label="身份证号" prop="idCard"><el-input v-model="form.idCard"/></el-form-item><el-form-item label="户籍地"><el-input v-model="form.hometown"/></el-form-item><el-row :gutter="14"><el-col :span="12"><el-form-item label="紧急联系人"><el-input v-model="form.emergencyContact"/></el-form-item></el-col><el-col :span="12"><el-form-item label="联系电话"><el-input v-model="form.emergencyPhone"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import{onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import http from'../api/http';import{useAuthStore}from'../stores/auth';const auth=useAuthStore(),statuses={PENDING:'待审核',LIVING:'居住中',REJECTED:'已驳回',MOVED_OUT:'已迁出'},statusType={PENDING:'warning',LIVING:'success',REJECTED:'danger',MOVED_OUT:'info'},query=reactive({pageNum:1,pageSize:10,keyword:'',status:''}),page=reactive({records:[],total:0}),loading=ref(false),dialog=ref(false),editing=ref(null),formRef=ref(),blank=()=>({userId:null,name:'',phone:'',idCard:'',gender:'男',hometown:'',emergencyContact:'',emergencyPhone:''}),form=reactive(blank()),rules={name:[{required:true,message:'请输入姓名'}],phone:[{required:true,message:'请输入手机号'}],idCard:[{required:true,message:'请输入身份证号'}]};onMounted(load);async function load(){loading.value=true;try{Object.assign(page,await http.get('/tenants',{params:query}))}finally{loading.value=false}}function reset(){query.keyword='';query.status='';query.pageNum=1;load()}function open(row){editing.value=row?.id||null;Object.assign(form,blank(),row||{});dialog.value=true}async function save(){await formRef.value.validate();editing.value?await http.put(`/tenants/${editing.value}`,form):await http.post('/tenants',form);ElMessage.success('档案已保存');dialog.value=false;load()}function maskId(v){return v&&v.length>8?v.slice(0,6)+'********'+v.slice(-4):v}
</script>
