<template>
  <div class="page-shell"><div class="page-heading"><div><h1>用户管理</h1><p>维护管理员、社区民警、房东和承租人账号。</p></div><el-button type="primary" @click="open()"><el-icon><Plus /></el-icon>新增用户</el-button></div>
    <section class="panel"><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="账号、姓名或手机号" style="width:250px" /><el-select v-model="query.role" clearable placeholder="全部角色" style="width:150px"><el-option v-for="(v,k) in roles" :key="k" :label="v" :value="k" /></el-select><el-select v-model="query.status" clearable placeholder="账号状态" style="width:130px"><el-option label="启用" :value="1"/><el-option label="禁用" :value="0"/></el-select><el-button @click="load"><el-icon><Search/></el-icon>查询</el-button><el-button @click="reset">重置</el-button></div>
      <div class="table-wrap"><el-table :data="page.records" v-loading="loading"><el-table-column prop="username" label="账号" min-width="120"><template #default="s"><span class="mono">{{s.row.username}}</span></template></el-table-column><el-table-column prop="realName" label="姓名" min-width="110"/><el-table-column prop="role" label="角色" width="110"><template #default="s"><el-tag :type="roleType[s.row.role]">{{roles[s.row.role]}}</el-tag></template></el-table-column><el-table-column prop="phone" label="手机号" width="135"/><el-table-column prop="policeNo" label="警号" width="110"/><el-table-column label="状态" width="85"><template #default="s"><span class="status-dot" :style="{background:s.row.status?'#0e8a7a':'#a9b6bc'}"></span>{{s.row.status?'启用':'禁用'}}</template></el-table-column><el-table-column prop="createdAt" label="创建时间" width="170"/><el-table-column label="操作" width="140" fixed="right"><template #default="s"><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-popconfirm title="确认删除账号？" @confirm="remove(s.row.id)"><template #reference><el-button link type="danger">删除</el-button></template></el-popconfirm></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.pageNum" :total="page.total" layout="total,prev,pager,next" @current-change="load"/></div></div></section>
    <el-dialog v-model="dialog" :title="editing?'编辑用户':'新增用户'" width="560px"><el-form ref="formRef" :model="form" :rules="rules" label-width="90px"><el-form-item v-if="!editing" label="登录账号" prop="username"><el-input v-model="form.username"/></el-form-item><el-form-item v-if="!editing" label="初始密码" prop="password"><el-input v-model="form.password" show-password/></el-form-item><el-form-item label="真实姓名" prop="realName"><el-input v-model="form.realName"/></el-form-item><el-form-item label="角色" prop="role"><el-select v-model="form.role" style="width:100%"><el-option v-for="(v,k) in roles" :key="k" :label="v" :value="k"/></el-select></el-form-item><el-form-item label="手机号"><el-input v-model="form.phone"/></el-form-item><el-form-item label="身份证号"><el-input v-model="form.idCard"/></el-form-item><el-form-item v-if="form.role==='POLICE'" label="警号"><el-input v-model="form.policeNo"/></el-form-item><el-form-item label="账号状态"><el-radio-group v-model="form.status"><el-radio :value="1">启用</el-radio><el-radio :value="0">禁用</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import {onMounted,reactive,ref} from 'vue';import{ElMessage}from'element-plus';import http from'../api/http'
const roles={ADMIN:'管理员',POLICE:'社区民警',OWNER:'房东',TENANT:'承租人'},roleType={ADMIN:'danger',POLICE:'primary',OWNER:'warning',TENANT:'success'}
const query=reactive({pageNum:1,pageSize:10,keyword:'',role:'',status:null}),page=reactive({records:[],total:0}),loading=ref(false),dialog=ref(false),editing=ref(null),formRef=ref();const blank=()=>({username:'',password:'123456',realName:'',phone:'',idCard:'',role:'OWNER',policeNo:'',status:1});const form=reactive(blank()),rules={username:[{required:true,message:'请输入账号'}],password:[{required:true,message:'请输入密码'}],realName:[{required:true,message:'请输入姓名'}],role:[{required:true,message:'请选择角色'}]}
onMounted(load);async function load(){loading.value=true;try{Object.assign(page,await http.get('/users',{params:query}))}finally{loading.value=false}}function reset(){Object.assign(query,{pageNum:1,pageSize:10,keyword:'',role:'',status:null});load()}function open(row){editing.value=row?.id||null;Object.assign(form,blank(),row||{});dialog.value=true}async function save(){await formRef.value.validate();editing.value?await http.put(`/users/${editing.value}`,form):await http.post('/users',form);ElMessage.success('保存成功');dialog.value=false;load()}async function remove(id){await http.delete(`/users/${id}`);ElMessage.success('删除成功');load()}
</script>
